name: Hola Mundo
on: [push]
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      env:
        MI_VARIABLE: Hola Mundo
      run: |
        echo $MI_VARIABLE

        

